version: "3.7"
services:
    postgresql:
        image: postgres:13
        container_name: postgres_master_hr
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
        volumes:
            - ./postgresql:/var/lib/postgresql/data

    odoo:
        build:
          context: .
          dockerfile: ./Dockerfile
        # image: hm3_py38-odoo
        platform: linux/amd64
        container_name: odoo_master_hr
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "2024:8069"
        volumes:
            - ../Equip3-moduleboard:/mnt/hm-addons
            - ./etc:/etc/odoo
        environment:
            - HOST=postgres_master_hr
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - USER=root